export const defaultStorage = {
  theme: "Dark",
  installed: [],
  favorites: [],
  keybinds: {},
  gamepadBinds: {},
  hiddenThemes: [],
  playTime: {},
  settings: {
    sidebarStyle: "default",
    category: "all",
    sortBy: "alphabetical",
    tagFilter: "all",
    maskTitle: "",
    maskIcon: "",
    panicKey: "",
    panicURL: "",
    aspect: "",
    closePrevention: false,
    customCSS: "",
    cards: "default",
    overlay: "default",
    libraryMode: false,
  },
};
