export const tags = [
  "2D",
  "2D Platformer",
  "3D",
  "3D Platformer",
  "8-Bit",
  "Action",
  "Action RPG",
  "Action-Adventure",
  "Adventure",
  "Arcade",
  "Atmospheric",
  "Board Game",
  "Building",
  "Card Game",
  "Cartoon",
  "Casual",
  "Clicker",
  "Co-Op",
  "Combat",
  "Comedy",
  "Crafting",
  "Cute",
  "Dark",
  "Deckbuilder",
  "Difficult",
  "Driving",
  "Endless",
  "Exploration",
  "Family Friendly",
  "Fantasy",
  "Fighting",
  "First-Person",
  "FPS",
  "Funny",
  "Futuristic",
  "Gore",
  "Hand-Drawn",
  "Horror",
  "Idle",
  "Incremental",
  "Indie",
  "Linear",
  "Logic",
  "Magic",
  "Management",
  "Math",
  "Medieval",
  "Minimalist",
  "Multiplayer",
  "Multiple Endings",
  "Mystery",
  "Old School",
  "Open World",
  "Physics",
  "Pixel Graphics",
  "Platformer",
  "Point & Click",
  "Procedural Generation",
  "Puzzle",
  "PvE",
  "PvP",
  "Racing",
  "Realistic",
  "Relaxing",
  "Resource Management",
  "Retro",
  "Roguelike",
  "Roguelite",
  "RPG",
  "Sandbox",
  "Sci-Fi",
  "Shooter",
  "Simulation",
  "Singleplayer",
  "Space",
  "Sports",
  "Story Rich",
  "Strategy",
  "Stylized",
  "Survival",
  "Tactical",
  "Third Person",
  "Top-Down",
  "Tower Defense",
  "Violent",
  "Visual Novel",
  "Word",
];
